model:
  name: 'osnet_x1_0'
  pretrained: True
  load_weights: 'new_log2006/osnet_x1_0_market1501_softmax/model/model.pth.tar-20'
  resume: 'new_log2006/osnet_x1_0_market1501_softmax/model/model.pth.tar-20'

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'color_jitter']
  save_dir: 'new_log2006_50ep/osnet_x1_0_market1501_softmax'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 50
  batch_size: 128
  fixbase_epoch: 10
  open_layers: ['classifier']
  lr_scheduler: 'single_step'
  stepsize: [20]

test:
  batch_size: 256
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  visrank: False
  eval_freq: 2
  rerank: False
  start_eval: 2
