model:
  name: 'resnet50_fc512'
  load_weights: 'new_log0909/resnet50_market1501_softmax/model/model.pth.tar-50'
  pretrained: True

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 256
  combineall: False
  transforms: ['random_flip']
  save_dir: 'new_log0909/resnet50_market1501_softmax'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0003
  max_epoch: 20
  batch_size: 64
  fixbase_epoch: 5
  open_layers: ['classifier']
  lr_scheduler: 'single_step'
  stepsize: [20]

test:
  batch_size: 256
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  visrank: False
  eval_freq: 2
  rerank: False
  start_eval: 2