model:
  name: 'resnet50_fc512'
  # load_weights: 'r50_market1501_triplet_model.pth.tar-50'
  # pretrained: True
  resume: 'r50_market1501_triplet2_model.pth.tar-46'

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'color_jitter', 'random_erase', 'random_blackwhite', 'random_perpective', 'random_rotation']
  save_dir: 'resutls/resnet50_market1501_triplet1'

loss:
  # name: 'softmax'
  # softmax:
  #   label_smooth: True
  name: 'triplet'
  softmax:
    label_smooth: True
  triplet:
    margin: 0.3
    weight_t: 0.5
    weight_x: 1.

train:
  optim: 'amsgrad'
  lr: 0.001
  max_epoch: 80
  batch_size: 512
  fixbase_epoch: 5
  open_layers: ['classifier']
  lr_scheduler: 'cosine'

test:
  batch_size: 64
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  visrank: False
  eval_freq: 2
  rerank: False
  start_eval: 2